# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: ".NET SDK 3.1.x"
    inputs:
      version: '3.1.x'
      packageType: sdk

  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: 'test'
      projects: '**/*.Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - task: DotNetCoreCLI@2
    displayName: "Publish"
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true
    condition: ne(variables['Build.Reason'], 'PullRequest')

  - task: PublishBuildArtifacts@1
    displayName: "Upload Artifacts"
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'futureGadgetLab'
    condition: ne(variables['Build.Reason'], 'PullRequest')